env:
  BUILDKITE_BUILD_PATH: "workdir_for_buildkit/ex1_hello_world" # NOTE1001: this is ignored and does not work

steps:
  - label: ":docker: Build image and deploy to Kind"
    #working_dir: "workdir_for_buildkit/ex1_hello_world" # NOTE1001: this does not work
    command:
      - "cd workdir_for_buildkit/ex1_hello_world" # NOTE1001: using cd in every step
      - "echo '--- Building Docker image'"
      - "docker build -t hello:latest ."

      - 'curl -fsSLo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.23.0/kind-linux-amd64'
      - 'chmod +x /usr/local/bin/kind'
      - 'curl -fsSLo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.30.2/bin/linux/amd64/kubectl'
      - 'chmod +x /usr/local/bin/kubectl'
      - 'curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash'

      - "echo '--- Loading image into Kind cluster'"
      - "kind load docker-image hello:latest --name kind"

      - "echo '--- Deploying manifests to Kind'"
      - "kubectl apply -f k8s/deployment.yaml"
      - "kubectl apply -f k8s/service.yaml"

      - "echo '--- Waiting for pod ready'"
      - "kubectl rollout status deploy/hello --timeout=60s"

      - "echo '--- Port-forward and test the app'"
      - "kubectl port-forward svc/hello 8080:80 &"
      - "sleep 3"
      - "curl -s http://localhost:8080"
