#!/usr/bin/env bash
set -euo pipefail
#set -x

identity="${BUILDKITE_PLUGIN_CGRAUTH_IDENTITY:?missing identity}"
cd workdir_for_buildkit/ex1_hello_world
curl -o chainctl https://dl.enforce.dev/chainctl/latest/chainctl_$(uname -s | tr "[:upper:]" "[:lower:]")_$(uname -m)
chmod +x chainctl
mv chainctl /usr/bin
token=$(buildkite-agent oidc request-token --audience issuer.enforce.dev)
chainctl auth login --identity-token $token --identity $identity
echo yahooooooooo
chainctl auth configure-docker --identity-token $token --identity $identity
echo yahooooooooo
#chainctl images repos list
